export default {
    editor: { label: { en: 'Tutorzy Meeting Room' }, icon: 'video-camera' },
    properties: {
        lessonId: { label: { en: 'Lesson ID' }, type: 'Text', bindable: true, section: 'settings', defaultValue: '' },
        roomToken: { label: { en: 'Room Token' }, type: 'Text', bindable: true, section: 'settings', defaultValue: '' },
        userRole: { label: { en: 'User Role' }, type: 'TextSelect', options: { options: [ { value: 'teacher', label: 'Teacher' }, { value: 'student', label: 'Student' } ] }, bindable: true, section: 'settings', defaultValue: 'student' },
        teacherName: { label: { en: 'Teacher Name' }, type: 'Text', bindable: true, section: 'settings', defaultValue: 'Teacher' },
        studentName: { label: { en: 'Student Name' }, type: 'Text', bindable: true, section: 'settings', defaultValue: 'Student' },
        teacherPhotoUrl: { label: { en: 'Teacher Photo URL' }, type: 'Text', bindable: true, section: 'settings', defaultValue: '' },
        studentPhotoUrl: { label: { en: 'Student Photo URL' }, type: 'Text', bindable: true, section: 'settings', defaultValue: '' },
        roomHeight: { label: { en: 'Room Height' }, type: 'Length', bindable: true, responsive: true, section: 'style', defaultValue: '600px' },
        themeColor: { label: { en: 'Theme Color' }, type: 'Color', bindable: true, section: 'style', defaultValue: '#007bff' },
        enableWhiteboard: { label: { en: 'Enable Whiteboard' }, type: 'OnOff', bindable: true, section: 'settings', defaultValue: true },
        enableScreenShare: { label: { en: 'Enable Screen Share' }, type: 'OnOff', bindable: true, section: 'settings', defaultValue: true },
        enableChat: { label: { en: 'Enable Chat' }, type: 'OnOff', bindable: true, section: 'settings', defaultValue: true },
        turnServerUrl: { label: { en: 'TURN Server URL' }, type: 'Text', bindable: true, section: 'settings', defaultValue: '' },
        turnUsername: { label: { en: 'TURN Username' }, type: 'Text', bindable: true, section: 'settings', defaultValue: '' },
        turnCredential: { label: { en: 'TURN Credential' }, type: 'Text', bindable: true, section: 'settings', defaultValue: '' },
        savedWhiteboardState: { label: { en: 'Saved Whiteboard State' }, type: 'Textarea', bindable: true, section: 'settings', defaultValue: '' },
        lessonTitle: { label: { en: 'Lesson Title' }, type: 'Text', bindable: true, section: 'settings', defaultValue: '' },
        lessonEndIso: { label: { en: 'Lesson End (ISO)' }, type: 'Text', bindable: true, section: 'settings', defaultValue: '' },
        showStatusBar: { label: { en: 'Show Status Bar' }, type: 'OnOff', bindable: true, section: 'settings', defaultValue: true },
        enableRaiseHand: { label: { en: 'Enable Raise Hand' }, type: 'OnOff', bindable: true, section: 'settings', defaultValue: true },
        enableReactions: { label: { en: 'Enable Reactions' }, type: 'OnOff', bindable: true, section: 'settings', defaultValue: true },
        enableFullscreen: { label: { en: 'Enable Fullscreen' }, type: 'OnOff', bindable: true, section: 'settings', defaultValue: true },
        enablePictureInPicture: { label: { en: 'PiP on Whiteboard' }, type: 'OnOff', bindable: true, section: 'settings', defaultValue: true },
        enablePipButton: { label: { en: 'Enable PiP Button' }, type: 'OnOff', bindable: true, section: 'settings', defaultValue: true },
        toolbarStyle: { label: { en: 'Toolbar Style' }, type: 'TextSelect', options: { options: [ { value: 'glass', label: 'Glass' }, { value: 'solid', label: 'Solid' } ] }, bindable: true, section: 'style', defaultValue: 'glass' },
    },
    actions: [
        { label: { en: 'Toggle Whiteboard' }, action: 'toggleWhiteboard' },
        { label: { en: 'Start Screen Share' }, action: 'startScreenShare' },
        { label: { en: 'Load Whiteboard State' }, action: 'loadWhiteboardState', args: [{ name: 'state', type: 'string', label: { en: 'State JSON' } }] },
    ],
    triggerEvents: [
        { name: 'callStarted', label: { en: 'On Call Start' }, event: { value: '' } },
        { name: 'callEnded', label: { en: 'On Leave' }, event: { value: '' } },
        { name: 'presence', label: { en: 'On Presence Tick' }, event: { value: '' } },
        { name: 'whiteboardChanged', label: { en: 'On Whiteboard Change' }, event: { value: '' }, default: true },
        { name: 'chatMessageSent', label: { en: 'On Chat Message' }, event: { value: {} } },
        { name: 'lateJoinReminderRequested', label: { en: 'On Late-Join Reminder Requested' }, event: { value: '' } },
    ],
};